
class Mensaje:
    title = "---------SuPropiedadRaiz-----------\n"
    bienv = "*Welcome, please select a language / Bienvenido, por favor  seleccione un idioma:*"
    gracias = "Gracias por visitarnos."
    en_es = "1. English. \n2. Espaniol"
    err = "Opcion incorrecta, intente de nuevo"

    menu_principal = "1. Agregar datos ficticios.\n2. Ingresar como propietario.\n3. Registrar cliente.\n4. Ingresar como cliente.\n5. Registro nuevo propietario \n6. Agregar datos ficticios desde txt(Clientes)\n0. Salir.\n"
    ingreso = "Para entrar, ingrese los siguientes datos:\n"
    registro = "Para registrarse, ingrese los siguientes datos:\n"
    err_datos = "Datos incorrectos, intente de nuevo"
    existe = "Ya existe este dato, intentelo de nuevo con uno diferente."

    bienv_usuario = "Bienvenido, "
    datosFicticios= "Datos ficticios agregados correctamente."
    seleccion = "----------------------------------------------------\n Ingrese el numero de una de las siguientes opciones: \n"
    menu_propietario = " 1. Registrar inmueble. \n 2. Ver lista de inmuebles. \n 3. Aprobar solicitudes de compraventa. \n 4. Aprobar solicitudes de arriendo. \n 0. Regresar al menu principal. \n " 

    menu_cliente = " 1. Ver ofertas de arrendamiento. \n 2. Ver ofertas de compraventa.\n "
    menu_cliente +="3. Seleccionar compraventa \n 4. Seleccionar arriendo \n "
    menu_cliente +="5. Mostrar mis contratos \n 6. ver ofertas de arrendamiento por estrato. \n "
    menu_cliente +="7. Ver ofertas de arrendamiento por numero de cuartos. \n 8. ver ofertas de arrendamiento por numero de baños. \n"
    menu_cliente +="0. Regresar al menu principal"

    arriendos_disp = "Los arrendamientos disponibles son: \n"
    compraventas_disp = "Las compraventas disponibles son: \n"
    sel_compraventa = "Ingrese el codigo de la compraventa: \n"
    sel_arriendo = "Ingrese el codigo del arriendo: \n"
    codigo_invalido ="Debe ingresar un codigo valido."
    ing = "por favor ingrese los siguientes datos: \n"
    para_reg = "Para registrar "
    nombre = "* Nombre: "
    cedula = "* Cedula: "
    correo = "* Correo: "
    opcional_correo = "Desea agregar un correo? :\n1. Si\n2. No"
    contrasena = "* Contrasena: "
    sueldo = "* Salario: "
    comision = "* Comision: "
    direccion = "* Direccion: "
    estrato = "* Estrato: "
    banos = "* Numero de banios: "
    cuartos = "* Numero de cuartos: "
    antiguedad = "* Anos de antiguedad: "
    area = "* Area en metros cuadrados: "
    ciudad = "* Ciudad del inmueble: "
    valor_mensual = "* Valor mensualidad: "
    valor = "* Precio: "
    inmueble = "inmueble: "
    inmueble_existe = "El inmueble ya existe."
    in_vigilancia = "Tiene vigilancia? (s|n): "
    in_ascensor = "Tiene ascensor? (s|n): "
    in_agencia = "Estara por medio de agencia? (s|n): "
    in_aplicar_compraventa = "Desea aplicar a esta compraventa (s|n): "
    in_aplicar_arriendo = "Desea aplicar a este arriendo (s|n): "
    medio_pago = "* Medio de pago: "
    creando_contrato = "**** Creando nuevo contrato de "
    compraventa = "compraventa: "
    arriendo = "arriendo: "
    fecha_inicio = "* Fecha donde inicia (formato dd/mm/aaaa): "
    fecha_fin = "* Fecha donde finaliza (formato dd/mm/aaaa): "
    fecha_actual = "* Fecha (formato dd/mm/aaaa)"

    tipo = "Registrar para arriendo o compraventa?: "
    agg = "Agregado correctamente.  \n"
    regd = "Registrado correctamente.  \n"

    reg_inmueble = "Debe registrar un inmueble.\n"

    apli_com = "Aplico a la compraventa."
    no_apli_com = "No aplico a la compraventa de codigo: "
    no_apli_arr = "No aplico al arriendo de codigo: "
    apli_arr = "Aplico al arriendo."

    cuartos_ini = "Ingrese el numero minimo de cuartos: "
    cuartos_top = "Ingrese el numero máximo de cuartos"
    estrato_ini = "Ingrese un estrato inicial: "
    estrato_top = "Ingrese un estrato final: "
    banios_ini = "Ingrese un numero de banios inicial: "
    banios_top = "Ingrese un numero de banios final: "


    aprobar_comp = "***** Aprobar solicitudes de compraventas *****"
    aprobar_arr = "***** Aprobar solicitudes de arriendo *****"
    no_mas_comp = "No tiene mas compraventas para aprobar."
    no_mas_arr = "No tiene mas arriendos para aprobar."
    desea_comp = "Desea aceptar la compraventa: "
    desea_arr = "Desea aceptar el arriendo: "
    vendido = "El inmueble se vendio con exito."
    arrendado = "El inmueble se arrendo con exito"
    anulada_comp = "La compraventa fue anulada y re-publicada con exito.\n"
    anulada_arr = "El arriendo fue anulado y re-publicado con exito.\n"
