
class Mensaje:
    title = "---------SuPropiedadRaiz-----------\n"
    bienv = "*Welcome, please select the language:*"
    gracias = "Thanks for your visit."
    en_es = "English"
    err = "Wrong option, please try again "

    menu_principal = " 1. Add testing data.\n 2. Log In as an owner. \n 3. Sign In as a Costumer. \n 4. Log In as a Customer.\n 5. Register new owner \n 6. Add testing data from txt (Customer)\n 0. Exit. \n "
    ingreso = "In order to Log In , enter the following data:\n"
    registro = "In order to Sign In, enter the following data:\n"
    err_datos = "Wrong data, please try again"
    existe = "This data already exists, please try again."

    bienv_usuario = "Welcome, "
    datosFicticios= "Testing data added succefully."

    seleccion = "----------------------------------------------------\n Enter a number fro one of the following options: \n"
    menu_propietario = " 1. Register a contract. \n 2. See list of properties. \n 0. Return to main menu. \n "
    menu_cliente = " 1. See rent offers. \n 2. See sale offers. \n 3. Select sale \n 4. Select rent \n "
    menu_cliente += "5. Show my contracts \n 6. See rent offers by social stratum \n " 
    menu_cliente += "7. See rent offers by number of rooms  \n 8. See rent offers by number of bathrooms "
    menu_cliente += "\n 0. Return to main menu"
    arriendos_disp = "The available rent offers are: \n"
    compraventas_disp = "The available sale offers are: \n"
    sel_compraventa = "Please enter the code of the sale: \n"
    sel_arriendo = "Please enter the code of the rent: \n"
    codigo_invalido ="Please enter a valid code."
    ing = "please enter the following data: \n"
    para_reg = "For register a new "
    nombre = "* name: "
    cedula = "* ID number: "
    correo = "* e-mail: "
    opcional_correo = "Do you want to add an email? :\n1. Yes\n2. No"
    contrasena = "* password: "
    sueldo = "* salary: "
    comision = "* bonus: "
    direccion = "* property address: "
    estrato = "* social stratum: "
    banos = "* number of baths: "
    cuartos = "* number of rooms: "
    antiguedad = "* years of antiquity: "
    area = "* area (square meters): "
    ciudad = "* city of the property: "
    valor_mensual = "* monthly payment: "
    valor = "* price: "
    inmueble = "property: "
    inmueble_existe = "the property already exists."
    in_vigilancia = "does the property have private security? (y|n): "
    in_ascensor = "does the property have elevator? (y|n): "
    in_agencia = "will the property have an agency? (y|n): "
    in_aplicar_compraventa = "do you want apply for this sale? (y|n): "
    in_aplicar_arriendo = "do you want apply for this rent? (y|n): "
    medio_pago = "* payment method: "
    creando_contrato = "**** Creating a new contract of "
    compraventa = "sale: "
    arriendo = "rent: "
    fecha_inicio = "* start date (format dd/mm/yyyy): "
    fecha_fin = "* finish date (format dd/mm/yyyy): "
    fecha_actual = "* date (format dd/mm/yyyy)"

    tipo = "Register for rent or sale?: "
    agg = "added succefully.  \n"
    regd = "registered succefully.  \n"

    apli_com = "Applied to the sale successfully."
    no_apli_com = "Failed to apply to the sale with code: "
    no_apli_arr = "Failed to apply to the rent with code: "
    apli_arr = "Applied to the rent successfully."

    cuartos_ini = "Please enter the minimum number of rooms: "
    cuartos_top = "Please enter the maximum number of rooms"
    estrato_ini = "Please enter the minimum social stratum: "
    estrato_top = "Please enter the maximum social stratum: "
    banios_ini = "Please enter the minimum number of bathrooms: "
    banios_top  = "Please enter the maximum number of bathrooms: "